---
title: Kleur toevoegen aan afbeeldingen
hero_image: images/banner.png
description: Kleur toevoegen aan afbeeldingen
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Kleur toevoegen aan afbeeldingen
