---
title: Añadir tinte a las imágenes
hero_image: images/banner.png
description: Añadir tinte a las imágenes
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Añadir tinte a las imágenes
