---
title: Ychwanegu arlliw at ddelweddau
hero_image: images/banner.png
description: Ychwanegu arlliw at ddelweddau
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Ychwanegu arlliw at ddelweddau
