---
title: Adiciona coloração às imagens
hero_image: images/banner.png
description: Adiciona coloração às imagens
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Adiciona coloração às imagens
