---
title: Dodaj odcień do obrazów
hero_image: images/banner.png
description: Dodaj odcień do obrazów
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Dodaj odcień do obrazów
