---
title: Ajouter tint aux images
hero_image: images/banner.png
description: Ajouter tint aux images
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Ajouter tint aux images
