---
title: Aggiungi tinta alle immagini
hero_image: images/banner.png
description: Aggiungi tinta alle immagini
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Aggiungi tinta alle immagini
